// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

type Globals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (g *Globals) GetXOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.XOrganizationID
}
