// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package censysassetgraphsdkgo

// Generated from OpenAPI doc version 1.0.4 and generator version 2.879.6

import (
	"fmt"
	"github.com/censys/censys-asset-graph-sdk-go/internal/config"
	"github.com/censys/censys-asset-graph-sdk-go/internal/hooks"
	"github.com/censys/censys-asset-graph-sdk-go/internal/utils"
	"github.com/censys/censys-asset-graph-sdk-go/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// Asset Graph API
	"https://graph.data.censys.io",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// SDK - Asset Graph API: # Asset Graph API
//
// The Asset Graph API provides comprehensive visibility into your Internet-facing assets. Use this API to build and manage attack surfaces by creating asset graphs, configuring seeds and exclusions, running discovery executions, and retrieving discovered assets and risk metadata.
//
// ### Authentication
//
// All requests must include a valid Censys personal access token (PAT) in the `Authorization` header:
//
// ```
// Authorization: Bearer <your-api-token>
// ```
//
// An `X-Organization-ID` header must also be present on every request. This identifies the Censys organization that owns the resources being accessed.
//
// ```
// X-Organization-ID: <your-organization-id>
// ```
//
// ### Core Concepts
//
// - **Asset Graph**: The parent resource representing an attack surface. Each asset graph contains seeds, excluded assets, and executions.
// - **Seeds**: Persistent starting points used to discover additional assets. Supported types include IP addresses, domains, CIDRs, ASNs, certificates, and web properties.
// - **Excluded Assets**: Assets explicitly excluded from the graph. Excluded assets will not appear in execution results and will not be used to discover additional assets.
// - **Executions**: A discovery process that uses the graph's configured seeds and excluded assets to generate a complete snapshot of the attack surface. Censys periodically runs executions in the background, or they can be triggered on-demand.
// - **Assets**: Internet-facing resources discovered during an execution, including hosts, domains, certificates, and web properties. Each asset includes discovery paths showing how it was found from your seeds.
// - **Risks**: Vulnerabilities, exposures, misconfigurations, and threats identified on discovered assets.
//
// ### Getting Started
//
// 1. **Create an asset graph** to represent your attack surface.
// 2. **Add seeds** — the known assets that Censys will use as starting points for discovery.
// 3. **Optionally add excluded assets** to omit specific assets from results.
// 4. **Create an execution** to trigger the discovery process, or wait for Censys to run one automatically.
// 5. **List assets** from a completed execution to view your discovered attack surface.
// 6. **Look up risk metadata** for any risk IDs found on your assets.
type SDK struct {
	SDKVersion      string
	AssetGraphs     *AssetGraphs
	ExcludedAssets  *ExcludedAssets
	GraphExecutions *GraphExecutions
	Assets          *Assets
	Seeds           *Seeds
	Risks           *Risks

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*SDK)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *SDK) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *SDK) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Client = client
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *SDK) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *SDK {
	sdk := &SDK{
		SDKVersion: "0.1.4",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.1.4 2.879.6 1.0.4 github.com/censys/censys-asset-graph-sdk-go",
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.AssetGraphs = newAssetGraphs(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.ExcludedAssets = newExcludedAssets(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.GraphExecutions = newGraphExecutions(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Assets = newAssets(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Seeds = newSeeds(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Risks = newRisks(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
