// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type CreateExcludedAssetGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (c *CreateExcludedAssetGlobals) GetXOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.XOrganizationID
}

type CreateExcludedAssetRequest struct {
	// Asset graph ID
	GraphID string                   `pathParam:"style=simple,explode=false,name=graph_id"`
	Body    components.AssetRefInput `request:"mediaType=application/json"`
}

func (c *CreateExcludedAssetRequest) GetGraphID() string {
	if c == nil {
		return ""
	}
	return c.GraphID
}

func (c *CreateExcludedAssetRequest) GetBody() components.AssetRefInput {
	if c == nil {
		return components.AssetRefInput{}
	}
	return c.Body
}

type CreateExcludedAssetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ExcludedAsset *components.ExcludedAsset
	// Error
	ErrorModel *components.ErrorModel
}

func (c *CreateExcludedAssetResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateExcludedAssetResponse) GetExcludedAsset() *components.ExcludedAsset {
	if c == nil {
		return nil
	}
	return c.ExcludedAsset
}

func (c *CreateExcludedAssetResponse) GetErrorModel() *components.ErrorModel {
	if c == nil {
		return nil
	}
	return c.ErrorModel
}
