// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type CreateAssetGraphGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (c *CreateAssetGraphGlobals) GetXOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.XOrganizationID
}

type CreateAssetGraphRequest struct {
	// Censys organization ID
	XOrganizationID *string                              `header:"style=simple,explode=false,name=X-Organization-ID"`
	Body            components.CreateAssetGraphInputBody `request:"mediaType=application/json"`
}

func (c *CreateAssetGraphRequest) GetXOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.XOrganizationID
}

func (c *CreateAssetGraphRequest) GetBody() components.CreateAssetGraphInputBody {
	if c == nil {
		return components.CreateAssetGraphInputBody{}
	}
	return c.Body
}

type CreateAssetGraphResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AssetGraph *components.AssetGraph
	// Error
	ErrorModel *components.ErrorModel
}

func (c *CreateAssetGraphResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAssetGraphResponse) GetAssetGraph() *components.AssetGraph {
	if c == nil {
		return nil
	}
	return c.AssetGraph
}

func (c *CreateAssetGraphResponse) GetErrorModel() *components.ErrorModel {
	if c == nil {
		return nil
	}
	return c.ErrorModel
}
