// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type CreateGraphExecutionGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (c *CreateGraphExecutionGlobals) GetXOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.XOrganizationID
}

type CreateGraphExecutionRequest struct {
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
}

func (c *CreateGraphExecutionRequest) GetGraphID() string {
	if c == nil {
		return ""
	}
	return c.GraphID
}

type CreateGraphExecutionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GraphExecution *components.GraphExecution
	// Error
	ErrorModel *components.ErrorModel
}

func (c *CreateGraphExecutionResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateGraphExecutionResponse) GetGraphExecution() *components.GraphExecution {
	if c == nil {
		return nil
	}
	return c.GraphExecution
}

func (c *CreateGraphExecutionResponse) GetErrorModel() *components.ErrorModel {
	if c == nil {
		return nil
	}
	return c.ErrorModel
}
