// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type CreateSeedGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (c *CreateSeedGlobals) GetXOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.XOrganizationID
}

type CreateSeedRequest struct {
	// Censys organization ID
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
	// Asset graph ID
	GraphID string                   `pathParam:"style=simple,explode=false,name=graph_id"`
	Body    components.AssetRefInput `request:"mediaType=application/json"`
}

func (c *CreateSeedRequest) GetXOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.XOrganizationID
}

func (c *CreateSeedRequest) GetGraphID() string {
	if c == nil {
		return ""
	}
	return c.GraphID
}

func (c *CreateSeedRequest) GetBody() components.AssetRefInput {
	if c == nil {
		return components.AssetRefInput{}
	}
	return c.Body
}

type CreateSeedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Seed *components.Seed
	// Error
	ErrorModel *components.ErrorModel
}

func (c *CreateSeedResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSeedResponse) GetSeed() *components.Seed {
	if c == nil {
		return nil
	}
	return c.Seed
}

func (c *CreateSeedResponse) GetErrorModel() *components.ErrorModel {
	if c == nil {
		return nil
	}
	return c.ErrorModel
}
