// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type DeleteAssetGraphGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (d *DeleteAssetGraphGlobals) GetXOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.XOrganizationID
}

type DeleteAssetGraphRequest struct {
	// Asset graph ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteAssetGraphRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteAssetGraphResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	ErrorModel *components.ErrorModel
}

func (d *DeleteAssetGraphResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteAssetGraphResponse) GetErrorModel() *components.ErrorModel {
	if d == nil {
		return nil
	}
	return d.ErrorModel
}
