// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type DeleteExcludedAssetRequest struct {
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Excluded asset identifier
	ExcludedAssetID string `pathParam:"style=simple,explode=false,name=excluded_asset_id"`
}

func (d *DeleteExcludedAssetRequest) GetGraphID() string {
	if d == nil {
		return ""
	}
	return d.GraphID
}

func (d *DeleteExcludedAssetRequest) GetExcludedAssetID() string {
	if d == nil {
		return ""
	}
	return d.ExcludedAssetID
}

type DeleteExcludedAssetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	ErrorModel *components.ErrorModel
}

func (d *DeleteExcludedAssetResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteExcludedAssetResponse) GetErrorModel() *components.ErrorModel {
	if d == nil {
		return nil
	}
	return d.ErrorModel
}
