// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type DeleteSeedRequest struct {
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Seed identifier
	SeedID string `pathParam:"style=simple,explode=false,name=seed_id"`
}

func (d *DeleteSeedRequest) GetGraphID() string {
	if d == nil {
		return ""
	}
	return d.GraphID
}

func (d *DeleteSeedRequest) GetSeedID() string {
	if d == nil {
		return ""
	}
	return d.SeedID
}

type DeleteSeedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	ErrorModel *components.ErrorModel
}

func (d *DeleteSeedResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteSeedResponse) GetErrorModel() *components.ErrorModel {
	if d == nil {
		return nil
	}
	return d.ErrorModel
}
