// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type GetAssetGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (g *GetAssetGlobals) GetXOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.XOrganizationID
}

type GetAssetRequest struct {
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Graph execution ID
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
	// Hex-encoded asset identifier
	AssetID string `pathParam:"style=simple,explode=false,name=asset_id"`
}

func (g *GetAssetRequest) GetGraphID() string {
	if g == nil {
		return ""
	}
	return g.GraphID
}

func (g *GetAssetRequest) GetExecutionID() string {
	if g == nil {
		return ""
	}
	return g.ExecutionID
}

func (g *GetAssetRequest) GetAssetID() string {
	if g == nil {
		return ""
	}
	return g.AssetID
}

type GetAssetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AssetResponse *components.AssetResponse
	// Error
	ErrorModel *components.ErrorModel
}

func (g *GetAssetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAssetResponse) GetAssetResponse() *components.AssetResponse {
	if g == nil {
		return nil
	}
	return g.AssetResponse
}

func (g *GetAssetResponse) GetErrorModel() *components.ErrorModel {
	if g == nil {
		return nil
	}
	return g.ErrorModel
}
