// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type GetAssetGraphRequest struct {
	// Asset graph ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetAssetGraphRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetAssetGraphResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AssetGraph *components.AssetGraph
	// Error
	ErrorModel *components.ErrorModel
}

func (g *GetAssetGraphResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAssetGraphResponse) GetAssetGraph() *components.AssetGraph {
	if g == nil {
		return nil
	}
	return g.AssetGraph
}

func (g *GetAssetGraphResponse) GetErrorModel() *components.ErrorModel {
	if g == nil {
		return nil
	}
	return g.ErrorModel
}
