// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type GetGraphExecutionRequest struct {
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Graph execution ID
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
}

func (g *GetGraphExecutionRequest) GetGraphID() string {
	if g == nil {
		return ""
	}
	return g.GraphID
}

func (g *GetGraphExecutionRequest) GetExecutionID() string {
	if g == nil {
		return ""
	}
	return g.ExecutionID
}

type GetGraphExecutionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GraphExecution *components.GraphExecution
	// Error
	ErrorModel *components.ErrorModel
}

func (g *GetGraphExecutionResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetGraphExecutionResponse) GetGraphExecution() *components.GraphExecution {
	if g == nil {
		return nil
	}
	return g.GraphExecution
}

func (g *GetGraphExecutionResponse) GetErrorModel() *components.ErrorModel {
	if g == nil {
		return nil
	}
	return g.ErrorModel
}
