// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type GetRiskMetadataGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (g *GetRiskMetadataGlobals) GetXOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.XOrganizationID
}

type GetRiskMetadataRequest struct {
	// Censys organization ID
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
	// A Censys risk ID (e.g. CENSYS-2025-1), threat ID (e.g. THREAT-1) or an external risk identifier (e.g. CVE-2025-00001)
	RiskID string `pathParam:"style=simple,explode=false,name=risk_id"`
}

func (g *GetRiskMetadataRequest) GetXOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.XOrganizationID
}

func (g *GetRiskMetadataRequest) GetRiskID() string {
	if g == nil {
		return ""
	}
	return g.RiskID
}

type GetRiskMetadataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	RiskMetadata *components.RiskMetadata
	// Error
	ErrorModel *components.ErrorModel
}

func (g *GetRiskMetadataResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRiskMetadataResponse) GetRiskMetadata() *components.RiskMetadata {
	if g == nil {
		return nil
	}
	return g.RiskMetadata
}

func (g *GetRiskMetadataResponse) GetErrorModel() *components.ErrorModel {
	if g == nil {
		return nil
	}
	return g.ErrorModel
}
