// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type ListExcludedAssetsGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (l *ListExcludedAssetsGlobals) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

type ListExcludedAssetsRequest struct {
	// Censys organization ID
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Pagination token from a previous response
	PageToken *string `queryParam:"style=form,explode=false,name=page_token"`
	// Maximum number of results to return
	PageSize *int `queryParam:"style=form,explode=false,name=page_size"`
}

func (l *ListExcludedAssetsRequest) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

func (l *ListExcludedAssetsRequest) GetGraphID() string {
	if l == nil {
		return ""
	}
	return l.GraphID
}

func (l *ListExcludedAssetsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

func (l *ListExcludedAssetsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListExcludedAssetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListExcludedAssetsOutputBody *components.ListExcludedAssetsOutputBody
	// Error
	ErrorModel *components.ErrorModel
}

func (l *ListExcludedAssetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListExcludedAssetsResponse) GetListExcludedAssetsOutputBody() *components.ListExcludedAssetsOutputBody {
	if l == nil {
		return nil
	}
	return l.ListExcludedAssetsOutputBody
}

func (l *ListExcludedAssetsResponse) GetErrorModel() *components.ErrorModel {
	if l == nil {
		return nil
	}
	return l.ErrorModel
}
