// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type ListShardsGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (l *ListShardsGlobals) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

type ListShardsRequest struct {
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Graph execution ID
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
	// Pagination token from a previous response
	PageToken *string `queryParam:"style=form,explode=false,name=page_token"`
	// Maximum number of results to return
	PageSize *int `queryParam:"style=form,explode=false,name=page_size"`
}

func (l *ListShardsRequest) GetGraphID() string {
	if l == nil {
		return ""
	}
	return l.GraphID
}

func (l *ListShardsRequest) GetExecutionID() string {
	if l == nil {
		return ""
	}
	return l.ExecutionID
}

func (l *ListShardsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

func (l *ListShardsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListShardsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListShardsOutputBody *components.ListShardsOutputBody
	// Error
	ErrorModel *components.ErrorModel
}

func (l *ListShardsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListShardsResponse) GetListShardsOutputBody() *components.ListShardsOutputBody {
	if l == nil {
		return nil
	}
	return l.ListShardsOutputBody
}

func (l *ListShardsResponse) GetErrorModel() *components.ErrorModel {
	if l == nil {
		return nil
	}
	return l.ErrorModel
}
