// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type ListAssetGraphsGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (l *ListAssetGraphsGlobals) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

type ListAssetGraphsRequest struct {
	// Censys organization ID
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
	// Pagination token from a previous response
	PageToken *string `queryParam:"style=form,explode=false,name=page_token"`
	// Maximum number of results to return
	PageSize *int `queryParam:"style=form,explode=false,name=page_size"`
}

func (l *ListAssetGraphsRequest) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

func (l *ListAssetGraphsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

func (l *ListAssetGraphsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListAssetGraphsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListAssetGraphsOutputBody *components.ListAssetGraphsOutputBody
	// Error
	ErrorModel *components.ErrorModel
}

func (l *ListAssetGraphsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAssetGraphsResponse) GetListAssetGraphsOutputBody() *components.ListAssetGraphsOutputBody {
	if l == nil {
		return nil
	}
	return l.ListAssetGraphsOutputBody
}

func (l *ListAssetGraphsResponse) GetErrorModel() *components.ErrorModel {
	if l == nil {
		return nil
	}
	return l.ErrorModel
}
