// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type ListAssetsGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (l *ListAssetsGlobals) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

type ListAssetsRequest struct {
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Graph execution ID
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
	// Pagination token from a previous response
	PageToken *string `queryParam:"style=form,explode=false,name=page_token"`
	// Maximum number of results to return
	PageSize *int `queryParam:"style=form,explode=false,name=page_size"`
	// If true, only return assets with risks
	Risks *bool `queryParam:"style=form,explode=false,name=risks"`
}

func (l *ListAssetsRequest) GetGraphID() string {
	if l == nil {
		return ""
	}
	return l.GraphID
}

func (l *ListAssetsRequest) GetExecutionID() string {
	if l == nil {
		return ""
	}
	return l.ExecutionID
}

func (l *ListAssetsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

func (l *ListAssetsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListAssetsRequest) GetRisks() *bool {
	if l == nil {
		return nil
	}
	return l.Risks
}

type ListAssetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListAssetsOutputBody *components.ListAssetsOutputBody
	// Error
	ErrorModel *components.ErrorModel
}

func (l *ListAssetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAssetsResponse) GetListAssetsOutputBody() *components.ListAssetsOutputBody {
	if l == nil {
		return nil
	}
	return l.ListAssetsOutputBody
}

func (l *ListAssetsResponse) GetErrorModel() *components.ErrorModel {
	if l == nil {
		return nil
	}
	return l.ErrorModel
}
