// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type ListSeedsGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (l *ListSeedsGlobals) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

type ListSeedsRequest struct {
	// Censys organization ID
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Pagination token from a previous response
	PageToken *string `queryParam:"style=form,explode=false,name=page_token"`
	// Maximum number of results to return
	PageSize *int `queryParam:"style=form,explode=false,name=page_size"`
}

func (l *ListSeedsRequest) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

func (l *ListSeedsRequest) GetGraphID() string {
	if l == nil {
		return ""
	}
	return l.GraphID
}

func (l *ListSeedsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

func (l *ListSeedsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListSeedsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListSeedsOutputBody *components.ListSeedsOutputBody
	// Error
	ErrorModel *components.ErrorModel
}

func (l *ListSeedsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSeedsResponse) GetListSeedsOutputBody() *components.ListSeedsOutputBody {
	if l == nil {
		return nil
	}
	return l.ListSeedsOutputBody
}

func (l *ListSeedsResponse) GetErrorModel() *components.ErrorModel {
	if l == nil {
		return nil
	}
	return l.ErrorModel
}
