// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/censys/censys-asset-graph-sdk-go/models/components"
)

type ListGraphExecutionsGlobals struct {
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
}

func (l *ListGraphExecutionsGlobals) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

type ListGraphExecutionsRequest struct {
	// Censys organization ID
	XOrganizationID *string `header:"style=simple,explode=false,name=X-Organization-ID"`
	// Asset graph ID
	GraphID string `pathParam:"style=simple,explode=false,name=graph_id"`
	// Pagination token from a previous response
	PageToken *string `queryParam:"style=form,explode=false,name=page_token"`
	// Maximum number of results to return
	PageSize *int `queryParam:"style=form,explode=false,name=page_size"`
}

func (l *ListGraphExecutionsRequest) GetXOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.XOrganizationID
}

func (l *ListGraphExecutionsRequest) GetGraphID() string {
	if l == nil {
		return ""
	}
	return l.GraphID
}

func (l *ListGraphExecutionsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

func (l *ListGraphExecutionsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListGraphExecutionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListGraphExecutionsOutputBody *components.ListGraphExecutionsOutputBody
	// Error
	ErrorModel *components.ErrorModel
}

func (l *ListGraphExecutionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListGraphExecutionsResponse) GetListGraphExecutionsOutputBody() *components.ListGraphExecutionsOutputBody {
	if l == nil {
		return nil
	}
	return l.ListGraphExecutionsOutputBody
}

func (l *ListGraphExecutionsResponse) GetErrorModel() *components.ErrorModel {
	if l == nil {
		return nil
	}
	return l.ErrorModel
}
