// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetRefInput struct {
	// Autonomous system number (ASN)
	AutonomousSystem *int `json:"autonomous_system,omitempty"`
	// Organization name
	BusinessOrganization *string `json:"business_organization,omitempty"`
	// SHA-256 fingerprint of a certificate (hex-encoded)
	Certificate *string `json:"certificate,omitempty"`
	// Domain name
	Domain *string `json:"domain,omitempty"`
	// IP address of a host
	Host *string `json:"host,omitempty"`
	// CIDR notation (e.g. 192.168.0.0/24)
	Netblock *string `json:"netblock,omitempty"`
	// Registrant email address
	RegistrantEmail *string `json:"registrant_email,omitempty"`
	// Registrant organization name
	RegistrantOrganization *string                `json:"registrant_organization,omitempty"`
	WebProperty            *WebPropertyIdentifier `json:"web_property,omitempty"`
}

func (a *AssetRefInput) GetAutonomousSystem() *int {
	if a == nil {
		return nil
	}
	return a.AutonomousSystem
}

func (a *AssetRefInput) GetBusinessOrganization() *string {
	if a == nil {
		return nil
	}
	return a.BusinessOrganization
}

func (a *AssetRefInput) GetCertificate() *string {
	if a == nil {
		return nil
	}
	return a.Certificate
}

func (a *AssetRefInput) GetDomain() *string {
	if a == nil {
		return nil
	}
	return a.Domain
}

func (a *AssetRefInput) GetHost() *string {
	if a == nil {
		return nil
	}
	return a.Host
}

func (a *AssetRefInput) GetNetblock() *string {
	if a == nil {
		return nil
	}
	return a.Netblock
}

func (a *AssetRefInput) GetRegistrantEmail() *string {
	if a == nil {
		return nil
	}
	return a.RegistrantEmail
}

func (a *AssetRefInput) GetRegistrantOrganization() *string {
	if a == nil {
		return nil
	}
	return a.RegistrantOrganization
}

func (a *AssetRefInput) GetWebProperty() *WebPropertyIdentifier {
	if a == nil {
		return nil
	}
	return a.WebProperty
}
