// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetResponse struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string      `json:"$schema,omitempty"`
	Certificate  *Certificate `json:"certificate,omitempty"`
	// Discovery paths to this asset
	DiscoveryPaths []DiscoveryPath `json:"discovery_paths,omitempty"`
	Domain         *DomainResponse `json:"domain,omitempty"`
	Host           *Host           `json:"host,omitempty"`
	// Unique identifier of the asset
	ID          string       `json:"id"`
	WebProperty *WebProperty `json:"web_property,omitempty"`
}

func (a *AssetResponse) GetDollarSchema() *string {
	if a == nil {
		return nil
	}
	return a.DollarSchema
}

func (a *AssetResponse) GetCertificate() *Certificate {
	if a == nil {
		return nil
	}
	return a.Certificate
}

func (a *AssetResponse) GetDiscoveryPaths() []DiscoveryPath {
	if a == nil {
		return nil
	}
	return a.DiscoveryPaths
}

func (a *AssetResponse) GetDomain() *DomainResponse {
	if a == nil {
		return nil
	}
	return a.Domain
}

func (a *AssetResponse) GetHost() *Host {
	if a == nil {
		return nil
	}
	return a.Host
}

func (a *AssetResponse) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AssetResponse) GetWebProperty() *WebProperty {
	if a == nil {
		return nil
	}
	return a.WebProperty
}
