// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetGraph struct {
	// A URL to the JSON Schema for this object.
	DollarSchema    *string         `json:"$schema,omitempty"`
	ActiveExecution *GraphExecution `json:"active_execution,omitempty"`
	// RFC3339 creation timestamp
	CreateTime string `json:"create_time"`
	// Optional description
	Description *string `json:"description,omitempty"`
	// Unique identifier for the asset graph
	ID string `json:"id"`
	// User-defined name
	Name string `json:"name"`
	// RFC3339 last-update timestamp
	UpdateTime string `json:"update_time"`
}

func (a *AssetGraph) GetDollarSchema() *string {
	if a == nil {
		return nil
	}
	return a.DollarSchema
}

func (a *AssetGraph) GetActiveExecution() *GraphExecution {
	if a == nil {
		return nil
	}
	return a.ActiveExecution
}

func (a *AssetGraph) GetCreateTime() string {
	if a == nil {
		return ""
	}
	return a.CreateTime
}

func (a *AssetGraph) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AssetGraph) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AssetGraph) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AssetGraph) GetUpdateTime() string {
	if a == nil {
		return ""
	}
	return a.UpdateTime
}
