// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetRef struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// Autonomous system number (ASN)
	AutonomousSystem *int `json:"autonomous_system,omitempty"`
	// Organization name
	BusinessOrganization *string `json:"business_organization,omitempty"`
	// SHA-256 fingerprint of a certificate (hex-encoded)
	Certificate *string `json:"certificate,omitempty"`
	// Domain name
	Domain *string `json:"domain,omitempty"`
	// IP address of a host
	Host *string `json:"host,omitempty"`
	// Asset id, matching the id returned by the get-asset endpoint. Populated on responses; ignored on input.
	ID *string `json:"id,omitempty"`
	// CIDR notation (e.g. 192.168.0.0/24)
	Netblock *string `json:"netblock,omitempty"`
	// Registrant email address
	RegistrantEmail *string `json:"registrant_email,omitempty"`
	// Registrant organization name
	RegistrantOrganization *string                `json:"registrant_organization,omitempty"`
	WebProperty            *WebPropertyIdentifier `json:"web_property,omitempty"`
}

func (a *AssetRef) GetDollarSchema() *string {
	if a == nil {
		return nil
	}
	return a.DollarSchema
}

func (a *AssetRef) GetAutonomousSystem() *int {
	if a == nil {
		return nil
	}
	return a.AutonomousSystem
}

func (a *AssetRef) GetBusinessOrganization() *string {
	if a == nil {
		return nil
	}
	return a.BusinessOrganization
}

func (a *AssetRef) GetCertificate() *string {
	if a == nil {
		return nil
	}
	return a.Certificate
}

func (a *AssetRef) GetDomain() *string {
	if a == nil {
		return nil
	}
	return a.Domain
}

func (a *AssetRef) GetHost() *string {
	if a == nil {
		return nil
	}
	return a.Host
}

func (a *AssetRef) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AssetRef) GetNetblock() *string {
	if a == nil {
		return nil
	}
	return a.Netblock
}

func (a *AssetRef) GetRegistrantEmail() *string {
	if a == nil {
		return nil
	}
	return a.RegistrantEmail
}

func (a *AssetRef) GetRegistrantOrganization() *string {
	if a == nil {
		return nil
	}
	return a.RegistrantOrganization
}

func (a *AssetRef) GetWebProperty() *WebPropertyIdentifier {
	if a == nil {
		return nil
	}
	return a.WebProperty
}
