// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateAssetGraphInputBody struct {
	// Optional description
	Description *string `json:"description,omitempty"`
	// User-defined name for this asset graph
	Name string `json:"name"`
}

func (c *CreateAssetGraphInputBody) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateAssetGraphInputBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
