// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CVSSComponentsAttackComplexity - Indicates conditions beyond the attacker’s control that must exist in order to exploit the vulnerability. The Attack Complexity metric is scored as either Low or High. There are two possible values: Low (L) – There are no specific pre-conditions required for exploitation, High (H) – The attacker must complete some number of preparatory steps in order to get access.
type CVSSComponentsAttackComplexity string

const (
	CVSSComponentsAttackComplexityUnknown CVSSComponentsAttackComplexity = ""
	CVSSComponentsAttackComplexityLow     CVSSComponentsAttackComplexity = "low"
	CVSSComponentsAttackComplexityHigh    CVSSComponentsAttackComplexity = "high"
)

func (e CVSSComponentsAttackComplexity) ToPointer() *CVSSComponentsAttackComplexity {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CVSSComponentsAttackComplexity) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "low", "high":
			return true
		}
	}
	return false
}

// CVSSComponentsAttackVector - Indicates the level of access required for an attacker to exploit the vulnerability. The Attack Vector metric is scored in one of four levels: Network (N) – Vulnerabilities with this rating are remotely exploitable, from one or more hops away, up to, and including, remote exploitation over the Internet, Adjacent (A) – A vulnerability with this rating requires network adjacency for exploitation. The attack must be launched from the same physical or logical network, Local (L) – Vulnerabilities with this rating are not exploitable over a network, Physical (P) – An attacker must physically interact with the target system.
type CVSSComponentsAttackVector string

const (
	CVSSComponentsAttackVectorUnknown  CVSSComponentsAttackVector = ""
	CVSSComponentsAttackVectorNetwork  CVSSComponentsAttackVector = "network"
	CVSSComponentsAttackVectorAdjacent CVSSComponentsAttackVector = "adjacent"
	CVSSComponentsAttackVectorLocal    CVSSComponentsAttackVector = "local"
	CVSSComponentsAttackVectorPhysical CVSSComponentsAttackVector = "physical"
)

func (e CVSSComponentsAttackVector) ToPointer() *CVSSComponentsAttackVector {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CVSSComponentsAttackVector) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "network", "adjacent", "local", "physical":
			return true
		}
	}
	return false
}

// CVSSComponentsAvailability - If an attack renders information unavailable, such as when a system crashes or through a DDoS attack, availability is negatively impacted. Availability has three possible values: None (N) – There is no loss of availability, Low (L) – Availability might be intermittently limited, or performance might be negatively impacted, as a result of a successful attack, High (H) – There is a complete loss of availability of the impacted system or information.
type CVSSComponentsAvailability string

const (
	CVSSComponentsAvailabilityUnknown CVSSComponentsAvailability = ""
	CVSSComponentsAvailabilityNone    CVSSComponentsAvailability = "none"
	CVSSComponentsAvailabilityLow     CVSSComponentsAvailability = "low"
	CVSSComponentsAvailabilityHigh    CVSSComponentsAvailability = "high"
)

func (e CVSSComponentsAvailability) ToPointer() *CVSSComponentsAvailability {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CVSSComponentsAvailability) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "none", "low", "high":
			return true
		}
	}
	return false
}

// CVSSComponentsConfidentiality - Refers to the disclosure of sensitive information to authorized and unauthorized users, with the goal being that only authorized users are able to access the target data. Confidentiality has three potential values: High (H) – The attacker has full access to all resources in the impacted system, including highly sensitive information such as encryption keys, Low (L) – The attacker has partial access to information, with no control over what, specifically, they are able to access, None (N) – No data is accessible to unauthorized users as a result of the exploit.
type CVSSComponentsConfidentiality string

const (
	CVSSComponentsConfidentialityUnknown CVSSComponentsConfidentiality = ""
	CVSSComponentsConfidentialityNone    CVSSComponentsConfidentiality = "none"
	CVSSComponentsConfidentialityLow     CVSSComponentsConfidentiality = "low"
	CVSSComponentsConfidentialityHigh    CVSSComponentsConfidentiality = "high"
)

func (e CVSSComponentsConfidentiality) ToPointer() *CVSSComponentsConfidentiality {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CVSSComponentsConfidentiality) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "none", "low", "high":
			return true
		}
	}
	return false
}

// CVSSComponentsIntegrity - Refers to whether the protected information has been tampered with or changed in any way. If there is no way for an attacker to alter the accuracy or completeness of the information, integrity has been maintained. Integrity has three values: None (N) – There is no loss of the integrity of any information, Low (L) – A limited amount of information might be tampered with or modified, but there is no serious impact on the protected system, High (H) – The attacker can modify any/all information on the target system, resulting in a complete loss of integrity.
type CVSSComponentsIntegrity string

const (
	CVSSComponentsIntegrityUnknown CVSSComponentsIntegrity = ""
	CVSSComponentsIntegrityNone    CVSSComponentsIntegrity = "none"
	CVSSComponentsIntegrityLow     CVSSComponentsIntegrity = "low"
	CVSSComponentsIntegrityHigh    CVSSComponentsIntegrity = "high"
)

func (e CVSSComponentsIntegrity) ToPointer() *CVSSComponentsIntegrity {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CVSSComponentsIntegrity) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "none", "low", "high":
			return true
		}
	}
	return false
}

// CVSSComponentsPrivilegesRequired - Describes the level of privileges or access an attacker must have before successful exploitation. There are three possible values: None (N) – There is no privilege or special access required to conduct the attack, Low (L) – The attacker requires basic, “user” level privileges to leverage the exploit, High (H) – Administrative or similar access privileges are required for successful attack.
type CVSSComponentsPrivilegesRequired string

const (
	CVSSComponentsPrivilegesRequiredUnknown CVSSComponentsPrivilegesRequired = ""
	CVSSComponentsPrivilegesRequiredNone    CVSSComponentsPrivilegesRequired = "none"
	CVSSComponentsPrivilegesRequiredLow     CVSSComponentsPrivilegesRequired = "low"
	CVSSComponentsPrivilegesRequiredHigh    CVSSComponentsPrivilegesRequired = "high"
)

func (e CVSSComponentsPrivilegesRequired) ToPointer() *CVSSComponentsPrivilegesRequired {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CVSSComponentsPrivilegesRequired) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "none", "low", "high":
			return true
		}
	}
	return false
}

// Scope - Determines whether a vulnerability in one system or component can impact another system or component. If a vulnerability in a vulnerable component can affect a component which is in a different security scope than the vulnerable component, a scope change occurs. Scope has two possible ratings: Changed (C) – An exploited vulnerability can have a carry over impact on another system, Unchanged (U) – The exploited vulnerability is limited in damage to only the local security authority.
type Scope string

const (
	ScopeUnknown   Scope = ""
	ScopeUnchanged Scope = "unchanged"
	ScopeChanged   Scope = "changed"
)

func (e Scope) ToPointer() *Scope {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Scope) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "unchanged", "changed":
			return true
		}
	}
	return false
}

// CVSSComponentsUserInteraction - Describes whether a user, other than the attacker, is required to do anything or participate in exploitation of the vulnerability. User interaction has two possible values: None (N) – No user interaction is required, Required (R) – A user must complete some steps for the exploit to succeed. For example, a user might be required to install some software.
type CVSSComponentsUserInteraction string

const (
	CVSSComponentsUserInteractionUnknown  CVSSComponentsUserInteraction = ""
	CVSSComponentsUserInteractionNone     CVSSComponentsUserInteraction = "none"
	CVSSComponentsUserInteractionRequired CVSSComponentsUserInteraction = "required"
)

func (e CVSSComponentsUserInteraction) ToPointer() *CVSSComponentsUserInteraction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CVSSComponentsUserInteraction) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "none", "required":
			return true
		}
	}
	return false
}

type CVSSComponents struct {
	// Indicates conditions beyond the attacker’s control that must exist in order to exploit the vulnerability. The Attack Complexity metric is scored as either Low or High. There are two possible values: Low (L) – There are no specific pre-conditions required for exploitation, High (H) – The attacker must complete some number of preparatory steps in order to get access.
	AttackComplexity *CVSSComponentsAttackComplexity `json:"attack_complexity,omitempty"`
	// Indicates the level of access required for an attacker to exploit the vulnerability. The Attack Vector metric is scored in one of four levels: Network (N) – Vulnerabilities with this rating are remotely exploitable, from one or more hops away, up to, and including, remote exploitation over the Internet, Adjacent (A) – A vulnerability with this rating requires network adjacency for exploitation. The attack must be launched from the same physical or logical network, Local (L) – Vulnerabilities with this rating are not exploitable over a network, Physical (P) – An attacker must physically interact with the target system.
	AttackVector *CVSSComponentsAttackVector `json:"attack_vector,omitempty"`
	// If an attack renders information unavailable, such as when a system crashes or through a DDoS attack, availability is negatively impacted. Availability has three possible values: None (N) – There is no loss of availability, Low (L) – Availability might be intermittently limited, or performance might be negatively impacted, as a result of a successful attack, High (H) – There is a complete loss of availability of the impacted system or information.
	Availability *CVSSComponentsAvailability `json:"availability,omitempty"`
	// Refers to the disclosure of sensitive information to authorized and unauthorized users, with the goal being that only authorized users are able to access the target data. Confidentiality has three potential values: High (H) – The attacker has full access to all resources in the impacted system, including highly sensitive information such as encryption keys, Low (L) – The attacker has partial access to information, with no control over what, specifically, they are able to access, None (N) – No data is accessible to unauthorized users as a result of the exploit.
	Confidentiality *CVSSComponentsConfidentiality `json:"confidentiality,omitempty"`
	// Refers to whether the protected information has been tampered with or changed in any way. If there is no way for an attacker to alter the accuracy or completeness of the information, integrity has been maintained. Integrity has three values: None (N) – There is no loss of the integrity of any information, Low (L) – A limited amount of information might be tampered with or modified, but there is no serious impact on the protected system, High (H) – The attacker can modify any/all information on the target system, resulting in a complete loss of integrity.
	Integrity *CVSSComponentsIntegrity `json:"integrity,omitempty"`
	// Describes the level of privileges or access an attacker must have before successful exploitation. There are three possible values: None (N) – There is no privilege or special access required to conduct the attack, Low (L) – The attacker requires basic, “user” level privileges to leverage the exploit, High (H) – Administrative or similar access privileges are required for successful attack.
	PrivilegesRequired *CVSSComponentsPrivilegesRequired `json:"privileges_required,omitempty"`
	// Determines whether a vulnerability in one system or component can impact another system or component. If a vulnerability in a vulnerable component can affect a component which is in a different security scope than the vulnerable component, a scope change occurs. Scope has two possible ratings: Changed (C) – An exploited vulnerability can have a carry over impact on another system, Unchanged (U) – The exploited vulnerability is limited in damage to only the local security authority.
	Scope *Scope `json:"scope,omitempty"`
	// Describes whether a user, other than the attacker, is required to do anything or participate in exploitation of the vulnerability. User interaction has two possible values: None (N) – No user interaction is required, Required (R) – A user must complete some steps for the exploit to succeed. For example, a user might be required to install some software.
	UserInteraction *CVSSComponentsUserInteraction `json:"user_interaction,omitempty"`
}

func (c *CVSSComponents) GetAttackComplexity() *CVSSComponentsAttackComplexity {
	if c == nil {
		return nil
	}
	return c.AttackComplexity
}

func (c *CVSSComponents) GetAttackVector() *CVSSComponentsAttackVector {
	if c == nil {
		return nil
	}
	return c.AttackVector
}

func (c *CVSSComponents) GetAvailability() *CVSSComponentsAvailability {
	if c == nil {
		return nil
	}
	return c.Availability
}

func (c *CVSSComponents) GetConfidentiality() *CVSSComponentsConfidentiality {
	if c == nil {
		return nil
	}
	return c.Confidentiality
}

func (c *CVSSComponents) GetIntegrity() *CVSSComponentsIntegrity {
	if c == nil {
		return nil
	}
	return c.Integrity
}

func (c *CVSSComponents) GetPrivilegesRequired() *CVSSComponentsPrivilegesRequired {
	if c == nil {
		return nil
	}
	return c.PrivilegesRequired
}

func (c *CVSSComponents) GetScope() *Scope {
	if c == nil {
		return nil
	}
	return c.Scope
}

func (c *CVSSComponents) GetUserInteraction() *CVSSComponentsUserInteraction {
	if c == nil {
		return nil
	}
	return c.UserInteraction
}
