// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DiscoveryPath struct {
	// Ordered segments forming the path
	Segments []PathSegment `json:"segments"`
}

func (d *DiscoveryPath) GetSegments() []PathSegment {
	if d == nil {
		return nil
	}
	return d.Segments
}
