// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DomainResponse struct {
	// Fully qualified domain name
	Fqdn string `json:"fqdn"`
}

func (d *DomainResponse) GetFqdn() string {
	if d == nil {
		return ""
	}
	return d.Fqdn
}
