// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-asset-graph-sdk-go/internal/utils"
)

type ErrorModel struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// Optional list of individual error details
	Errors []ErrorDetail `json:"errors,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`
	// HTTP status code
	Status *int64 `json:"status,omitempty"`
	// A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`
	// A URI reference to human-readable documentation for the error.
	Type *string `default:"about:blank" json:"type"`
}

func (e ErrorModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ErrorModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ErrorModel) GetDollarSchema() *string {
	if e == nil {
		return nil
	}
	return e.DollarSchema
}

func (e *ErrorModel) GetDetail() *string {
	if e == nil {
		return nil
	}
	return e.Detail
}

func (e *ErrorModel) GetErrors() []ErrorDetail {
	if e == nil {
		return nil
	}
	return e.Errors
}

func (e *ErrorModel) GetInstance() *string {
	if e == nil {
		return nil
	}
	return e.Instance
}

func (e *ErrorModel) GetStatus() *int64 {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *ErrorModel) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *ErrorModel) GetType() *string {
	if e == nil {
		return nil
	}
	return e.Type
}
