// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ExcludedAsset struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// Autonomous system number (ASN)
	AutonomousSystem *int `json:"autonomous_system,omitempty"`
	// Organization name
	BusinessOrganization *string `json:"business_organization,omitempty"`
	// SHA-256 fingerprint of a certificate (hex-encoded)
	Certificate *string `json:"certificate,omitempty"`
	// RFC3339 creation timestamp
	CreateTime *string `json:"create_time,omitempty"`
	// Domain name
	Domain *string `json:"domain,omitempty"`
	// IP address of a host
	Host *string `json:"host,omitempty"`
	// Unique identifier for the excluded asset
	ID string `json:"id"`
	// CIDR notation (e.g. 192.168.0.0/24)
	Netblock *string `json:"netblock,omitempty"`
	// Registrant email address
	RegistrantEmail *string `json:"registrant_email,omitempty"`
	// Registrant organization name
	RegistrantOrganization *string                `json:"registrant_organization,omitempty"`
	WebProperty            *WebPropertyIdentifier `json:"web_property,omitempty"`
}

func (e *ExcludedAsset) GetDollarSchema() *string {
	if e == nil {
		return nil
	}
	return e.DollarSchema
}

func (e *ExcludedAsset) GetAutonomousSystem() *int {
	if e == nil {
		return nil
	}
	return e.AutonomousSystem
}

func (e *ExcludedAsset) GetBusinessOrganization() *string {
	if e == nil {
		return nil
	}
	return e.BusinessOrganization
}

func (e *ExcludedAsset) GetCertificate() *string {
	if e == nil {
		return nil
	}
	return e.Certificate
}

func (e *ExcludedAsset) GetCreateTime() *string {
	if e == nil {
		return nil
	}
	return e.CreateTime
}

func (e *ExcludedAsset) GetDomain() *string {
	if e == nil {
		return nil
	}
	return e.Domain
}

func (e *ExcludedAsset) GetHost() *string {
	if e == nil {
		return nil
	}
	return e.Host
}

func (e *ExcludedAsset) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExcludedAsset) GetNetblock() *string {
	if e == nil {
		return nil
	}
	return e.Netblock
}

func (e *ExcludedAsset) GetRegistrantEmail() *string {
	if e == nil {
		return nil
	}
	return e.RegistrantEmail
}

func (e *ExcludedAsset) GetRegistrantOrganization() *string {
	if e == nil {
		return nil
	}
	return e.RegistrantOrganization
}

func (e *ExcludedAsset) GetWebProperty() *WebPropertyIdentifier {
	if e == nil {
		return nil
	}
	return e.WebProperty
}
