// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ExecutionStats struct {
	// Number of discovered (non-seed) certificate assets
	DiscoveredCertificates int64 `json:"discovered_certificates"`
	// Number of discovered (non-seed) domain assets
	DiscoveredDomains int64 `json:"discovered_domains"`
	// Number of discovered (non-seed) host assets
	DiscoveredHosts int64 `json:"discovered_hosts"`
	// Number of discovered (non-seed) web property assets
	DiscoveredWebProperties int64 `json:"discovered_web_properties"`
	// Number of host assets with risks
	HostsWithRisks int64 `json:"hosts_with_risks"`
	// Total number of certificate assets
	TotalCertificates int64 `json:"total_certificates"`
	// Total number of domain assets
	TotalDomains int64 `json:"total_domains"`
	// Total number of host assets
	TotalHosts int64 `json:"total_hosts"`
	// Total number of web property assets
	TotalWebProperties int64 `json:"total_web_properties"`
	// Number of web property assets with risks
	WebPropertiesWithRisks int64 `json:"web_properties_with_risks"`
}

func (e *ExecutionStats) GetDiscoveredCertificates() int64 {
	if e == nil {
		return 0
	}
	return e.DiscoveredCertificates
}

func (e *ExecutionStats) GetDiscoveredDomains() int64 {
	if e == nil {
		return 0
	}
	return e.DiscoveredDomains
}

func (e *ExecutionStats) GetDiscoveredHosts() int64 {
	if e == nil {
		return 0
	}
	return e.DiscoveredHosts
}

func (e *ExecutionStats) GetDiscoveredWebProperties() int64 {
	if e == nil {
		return 0
	}
	return e.DiscoveredWebProperties
}

func (e *ExecutionStats) GetHostsWithRisks() int64 {
	if e == nil {
		return 0
	}
	return e.HostsWithRisks
}

func (e *ExecutionStats) GetTotalCertificates() int64 {
	if e == nil {
		return 0
	}
	return e.TotalCertificates
}

func (e *ExecutionStats) GetTotalDomains() int64 {
	if e == nil {
		return 0
	}
	return e.TotalDomains
}

func (e *ExecutionStats) GetTotalHosts() int64 {
	if e == nil {
		return 0
	}
	return e.TotalHosts
}

func (e *ExecutionStats) GetTotalWebProperties() int64 {
	if e == nil {
		return 0
	}
	return e.TotalWebProperties
}

func (e *ExecutionStats) GetWebPropertiesWithRisks() int64 {
	if e == nil {
		return 0
	}
	return e.WebPropertiesWithRisks
}
