// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GraphExecution struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// RFC3339 creation timestamp
	CreateTime string `json:"create_time"`
	// Unique identifier for the execution
	ID    string          `json:"id"`
	Stats *ExecutionStats `json:"stats,omitempty"`
	// Execution status
	Status string `json:"status"`
	// RFC3339 last-update timestamp
	UpdateTime string `json:"update_time"`
}

func (g *GraphExecution) GetDollarSchema() *string {
	if g == nil {
		return nil
	}
	return g.DollarSchema
}

func (g *GraphExecution) GetCreateTime() string {
	if g == nil {
		return ""
	}
	return g.CreateTime
}

func (g *GraphExecution) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GraphExecution) GetStats() *ExecutionStats {
	if g == nil {
		return nil
	}
	return g.Stats
}

func (g *GraphExecution) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GraphExecution) GetUpdateTime() string {
	if g == nil {
		return ""
	}
	return g.UpdateTime
}
