// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListAssetsOutputBody struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// List of assets
	Assets []AssetResponse `json:"assets"`
	// Token for the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
}

func (l *ListAssetsOutputBody) GetDollarSchema() *string {
	if l == nil {
		return nil
	}
	return l.DollarSchema
}

func (l *ListAssetsOutputBody) GetAssets() []AssetResponse {
	if l == nil {
		return nil
	}
	return l.Assets
}

func (l *ListAssetsOutputBody) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}
