// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListShardsOutputBody struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// Token for the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
	// List of shards
	Shards []ShardResponse `json:"shards"`
}

func (l *ListShardsOutputBody) GetDollarSchema() *string {
	if l == nil {
		return nil
	}
	return l.DollarSchema
}

func (l *ListShardsOutputBody) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}

func (l *ListShardsOutputBody) GetShards() []ShardResponse {
	if l == nil {
		return nil
	}
	return l.Shards
}
