// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListExcludedAssetsOutputBody struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// List of excluded assets
	ExcludedAssets []ExcludedAsset `json:"excluded_assets"`
	// Token for the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
}

func (l *ListExcludedAssetsOutputBody) GetDollarSchema() *string {
	if l == nil {
		return nil
	}
	return l.DollarSchema
}

func (l *ListExcludedAssetsOutputBody) GetExcludedAssets() []ExcludedAsset {
	if l == nil {
		return nil
	}
	return l.ExcludedAssets
}

func (l *ListExcludedAssetsOutputBody) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}
