// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListSeedsOutputBody struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// Token for the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
	// List of seeds
	Seeds []Seed `json:"seeds"`
}

func (l *ListSeedsOutputBody) GetDollarSchema() *string {
	if l == nil {
		return nil
	}
	return l.DollarSchema
}

func (l *ListSeedsOutputBody) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}

func (l *ListSeedsOutputBody) GetSeeds() []Seed {
	if l == nil {
		return nil
	}
	return l.Seeds
}
