// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListAssetGraphsOutputBody struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// List of asset graphs
	AssetGraphs []AssetGraph `json:"asset_graphs"`
	// Token for the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
}

func (l *ListAssetGraphsOutputBody) GetDollarSchema() *string {
	if l == nil {
		return nil
	}
	return l.DollarSchema
}

func (l *ListAssetGraphsOutputBody) GetAssetGraphs() []AssetGraph {
	if l == nil {
		return nil
	}
	return l.AssetGraphs
}

func (l *ListAssetGraphsOutputBody) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}
