// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListGraphExecutionsOutputBody struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// List of graph executions
	Executions []GraphExecution `json:"executions"`
	// Token for the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
}

func (l *ListGraphExecutionsOutputBody) GetDollarSchema() *string {
	if l == nil {
		return nil
	}
	return l.DollarSchema
}

func (l *ListGraphExecutionsOutputBody) GetExecutions() []GraphExecution {
	if l == nil {
		return nil
	}
	return l.Executions
}

func (l *ListGraphExecutionsOutputBody) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}
