// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PathRelationship struct {
	// Edge type (e.g. FORWARD_DNS)
	Type string `json:"type"`
}

func (p *PathRelationship) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}
