// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PathRelationship struct {
	// Edge type (e.g. FORWARD_DNS)
	Type string `json:"type"`
	// Edge weight from 0 to 1.0; lower means higher-confidence discovery
	Weight *float64 `json:"weight,omitempty"`
}

func (p *PathRelationship) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *PathRelationship) GetWeight() *float64 {
	if p == nil {
		return nil
	}
	return p.Weight
}
