// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PathSegment struct {
	End          AssetRef         `json:"end"`
	Relationship PathRelationship `json:"relationship"`
	Start        AssetRef         `json:"start"`
}

func (p *PathSegment) GetEnd() AssetRef {
	if p == nil {
		return AssetRef{}
	}
	return p.End
}

func (p *PathSegment) GetRelationship() PathRelationship {
	if p == nil {
		return PathRelationship{}
	}
	return p.Relationship
}

func (p *PathSegment) GetStart() AssetRef {
	if p == nil {
		return AssetRef{}
	}
	return p.Start
}
