// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PathSegment struct {
	End          SegmentVertex    `json:"end"`
	Relationship PathRelationship `json:"relationship"`
	Start        SegmentVertex    `json:"start"`
}

func (p *PathSegment) GetEnd() SegmentVertex {
	if p == nil {
		return SegmentVertex{}
	}
	return p.End
}

func (p *PathSegment) GetRelationship() PathRelationship {
	if p == nil {
		return PathRelationship{}
	}
	return p.Relationship
}

func (p *PathSegment) GetStart() SegmentVertex {
	if p == nil {
		return SegmentVertex{}
	}
	return p.Start
}
