// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Reference struct {
	Link string `json:"link"`
}

func (r *Reference) GetLink() string {
	if r == nil {
		return ""
	}
	return r.Link
}
