// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/censys/censys-asset-graph-sdk-go/internal/utils"
	"time"
)

type RiskMetadata struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// Time data was ingested
	AddedAt time.Time `json:"added_at"`
	// Description of the risk
	Description string `json:"description"`
	// Name of the risk
	Name string `json:"name"`
	// Reference information for data returned
	References []Reference `json:"references"`
}

func (r RiskMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RiskMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RiskMetadata) GetDollarSchema() *string {
	if r == nil {
		return nil
	}
	return r.DollarSchema
}

func (r *RiskMetadata) GetAddedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.AddedAt
}

func (r *RiskMetadata) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}

func (r *RiskMetadata) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RiskMetadata) GetReferences() []Reference {
	if r == nil {
		return nil
	}
	return r.References
}
