// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RiskRiskSource string

const (
	RiskRiskSourceUnknown RiskRiskSource = ""
	RiskRiskSourceCensys  RiskRiskSource = "censys"
	RiskRiskSourceCve     RiskRiskSource = "cve"
)

func (e RiskRiskSource) ToPointer() *RiskRiskSource {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RiskRiskSource) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "censys", "cve":
			return true
		}
	}
	return false
}

type RiskSeverity string

const (
	RiskSeverityUnknown  RiskSeverity = ""
	RiskSeverityLow      RiskSeverity = "low"
	RiskSeverityMedium   RiskSeverity = "medium"
	RiskSeverityHigh     RiskSeverity = "high"
	RiskSeverityCritical RiskSeverity = "critical"
)

func (e RiskSeverity) ToPointer() *RiskSeverity {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RiskSeverity) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "low", "medium", "high", "critical":
			return true
		}
	}
	return false
}

type RiskSource string

const (
	RiskSourceUnknown           RiskSource = ""
	RiskSourceCensys            RiskSource = "censys"
	RiskSourceRecog             RiskSource = "recog"
	RiskSourceWappalyzer        RiskSource = "wappalyzer"
	RiskSourceThirdParty        RiskSource = "third_party"
	RiskSourceHTMLMetaExtractor RiskSource = "html_meta_extractor"
)

func (e RiskSource) ToPointer() *RiskSource {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RiskSource) IsExact() bool {
	if e != nil {
		switch *e {
		case "", "censys", "recog", "wappalyzer", "third_party", "html_meta_extractor":
			return true
		}
	}
	return false
}

type Risk struct {
	Confidence *float64        `json:"confidence,omitempty"`
	Cvss       *Cvss           `json:"cvss,omitempty"`
	Evidence   []Evidence      `json:"evidence,omitempty"`
	ID         *string         `json:"id,omitempty"`
	Metrics    *Metrics        `json:"metrics,omitempty"`
	Name       *string         `json:"name,omitempty"`
	RiskSource *RiskRiskSource `json:"risk_source,omitempty"`
	Severity   *RiskSeverity   `json:"severity,omitempty"`
	Source     *RiskSource     `json:"source,omitempty"`
	Year       *int            `json:"year,omitempty"`
}

func (r *Risk) GetConfidence() *float64 {
	if r == nil {
		return nil
	}
	return r.Confidence
}

func (r *Risk) GetCvss() *Cvss {
	if r == nil {
		return nil
	}
	return r.Cvss
}

func (r *Risk) GetEvidence() []Evidence {
	if r == nil {
		return nil
	}
	return r.Evidence
}

func (r *Risk) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *Risk) GetMetrics() *Metrics {
	if r == nil {
		return nil
	}
	return r.Metrics
}

func (r *Risk) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *Risk) GetRiskSource() *RiskRiskSource {
	if r == nil {
		return nil
	}
	return r.RiskSource
}

func (r *Risk) GetSeverity() *RiskSeverity {
	if r == nil {
		return nil
	}
	return r.Severity
}

func (r *Risk) GetSource() *RiskSource {
	if r == nil {
		return nil
	}
	return r.Source
}

func (r *Risk) GetYear() *int {
	if r == nil {
		return nil
	}
	return r.Year
}
