// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Seed struct {
	// A URL to the JSON Schema for this object.
	DollarSchema *string `json:"$schema,omitempty"`
	// Autonomous system number (ASN)
	AutonomousSystem *int `json:"autonomous_system,omitempty"`
	// Organization name
	BusinessOrganization *string `json:"business_organization,omitempty"`
	// SHA-256 fingerprint of a certificate (hex-encoded)
	Certificate *string `json:"certificate,omitempty"`
	// RFC3339 creation timestamp
	CreateTime *string `json:"create_time,omitempty"`
	// Domain name
	Domain *string `json:"domain,omitempty"`
	// IP address of a host
	Host *string `json:"host,omitempty"`
	// Unique identifier for the seed
	ID string `json:"id"`
	// CIDR notation (e.g. 192.168.0.0/24)
	Netblock *string `json:"netblock,omitempty"`
	// Registrant email address
	RegistrantEmail *string `json:"registrant_email,omitempty"`
	// Registrant organization name
	RegistrantOrganization *string                `json:"registrant_organization,omitempty"`
	WebProperty            *WebPropertyIdentifier `json:"web_property,omitempty"`
}

func (s *Seed) GetDollarSchema() *string {
	if s == nil {
		return nil
	}
	return s.DollarSchema
}

func (s *Seed) GetAutonomousSystem() *int {
	if s == nil {
		return nil
	}
	return s.AutonomousSystem
}

func (s *Seed) GetBusinessOrganization() *string {
	if s == nil {
		return nil
	}
	return s.BusinessOrganization
}

func (s *Seed) GetCertificate() *string {
	if s == nil {
		return nil
	}
	return s.Certificate
}

func (s *Seed) GetCreateTime() *string {
	if s == nil {
		return nil
	}
	return s.CreateTime
}

func (s *Seed) GetDomain() *string {
	if s == nil {
		return nil
	}
	return s.Domain
}

func (s *Seed) GetHost() *string {
	if s == nil {
		return nil
	}
	return s.Host
}

func (s *Seed) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Seed) GetNetblock() *string {
	if s == nil {
		return nil
	}
	return s.Netblock
}

func (s *Seed) GetRegistrantEmail() *string {
	if s == nil {
		return nil
	}
	return s.RegistrantEmail
}

func (s *Seed) GetRegistrantOrganization() *string {
	if s == nil {
		return nil
	}
	return s.RegistrantOrganization
}

func (s *Seed) GetWebProperty() *WebPropertyIdentifier {
	if s == nil {
		return nil
	}
	return s.WebProperty
}
