// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SegmentVertex struct {
	// Autonomous system number (ASN)
	AutonomousSystem *int `json:"autonomous_system,omitempty"`
	// Organization name
	BusinessOrganization *string `json:"business_organization,omitempty"`
	// SHA-256 fingerprint of a certificate (hex-encoded)
	Certificate *string `json:"certificate,omitempty"`
	// Domain name
	Domain *string `json:"domain,omitempty"`
	// IP address of a host
	Host *string `json:"host,omitempty"`
	// Asset id, matching the id on the asset returned by the get-assets endpoint
	ID string `json:"id"`
	// CIDR notation (e.g. 192.168.0.0/24)
	Netblock *string `json:"netblock,omitempty"`
	// Registrant email address
	RegistrantEmail *string `json:"registrant_email,omitempty"`
	// Registrant organization name
	RegistrantOrganization *string                `json:"registrant_organization,omitempty"`
	WebProperty            *WebPropertyIdentifier `json:"web_property,omitempty"`
}

func (s *SegmentVertex) GetAutonomousSystem() *int {
	if s == nil {
		return nil
	}
	return s.AutonomousSystem
}

func (s *SegmentVertex) GetBusinessOrganization() *string {
	if s == nil {
		return nil
	}
	return s.BusinessOrganization
}

func (s *SegmentVertex) GetCertificate() *string {
	if s == nil {
		return nil
	}
	return s.Certificate
}

func (s *SegmentVertex) GetDomain() *string {
	if s == nil {
		return nil
	}
	return s.Domain
}

func (s *SegmentVertex) GetHost() *string {
	if s == nil {
		return nil
	}
	return s.Host
}

func (s *SegmentVertex) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SegmentVertex) GetNetblock() *string {
	if s == nil {
		return nil
	}
	return s.Netblock
}

func (s *SegmentVertex) GetRegistrantEmail() *string {
	if s == nil {
		return nil
	}
	return s.RegistrantEmail
}

func (s *SegmentVertex) GetRegistrantOrganization() *string {
	if s == nil {
		return nil
	}
	return s.RegistrantOrganization
}

func (s *SegmentVertex) GetWebProperty() *WebPropertyIdentifier {
	if s == nil {
		return nil
	}
	return s.WebProperty
}
