// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ShardResponse struct {
	// Shard identifier
	ID string `json:"id"`
}

func (s *ShardResponse) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}
