// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebPropertyIdentifier struct {
	// Hostname of the web property
	Hostname string `json:"hostname"`
	// Port of the web property
	Port int `json:"port"`
}

func (w *WebPropertyIdentifier) GetHostname() string {
	if w == nil {
		return ""
	}
	return w.Hostname
}

func (w *WebPropertyIdentifier) GetPort() int {
	if w == nil {
		return 0
	}
	return w.Port
}
