// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebProperty struct {
	Cert             *Certificate        `json:"cert,omitempty"`
	Endpoints        []EndpointScanState `json:"endpoints,omitempty"`
	Exposures        []Risk              `json:"exposures,omitempty"`
	Hardware         []Attribute         `json:"hardware,omitempty"`
	Hostname         *string             `json:"hostname,omitempty"`
	Jarm             *JarmScan           `json:"jarm,omitempty"`
	Labels           []Label             `json:"labels,omitempty"`
	Misconfigs       []Risk              `json:"misconfigs,omitempty"`
	OperatingSystems []Attribute         `json:"operating_systems,omitempty"`
	Port             *int                `json:"port,omitempty"`
	ScanTime         *string             `json:"scan_time,omitempty"`
	Software         []Attribute         `json:"software,omitempty"`
	Threats          []Threat            `json:"threats,omitempty"`
	TLS              *TLS                `json:"tls,omitempty"`
	Vulns            []Vuln              `json:"vulns,omitempty"`
}

func (w *WebProperty) GetCert() *Certificate {
	if w == nil {
		return nil
	}
	return w.Cert
}

func (w *WebProperty) GetEndpoints() []EndpointScanState {
	if w == nil {
		return nil
	}
	return w.Endpoints
}

func (w *WebProperty) GetExposures() []Risk {
	if w == nil {
		return nil
	}
	return w.Exposures
}

func (w *WebProperty) GetHardware() []Attribute {
	if w == nil {
		return nil
	}
	return w.Hardware
}

func (w *WebProperty) GetHostname() *string {
	if w == nil {
		return nil
	}
	return w.Hostname
}

func (w *WebProperty) GetJarm() *JarmScan {
	if w == nil {
		return nil
	}
	return w.Jarm
}

func (w *WebProperty) GetLabels() []Label {
	if w == nil {
		return nil
	}
	return w.Labels
}

func (w *WebProperty) GetMisconfigs() []Risk {
	if w == nil {
		return nil
	}
	return w.Misconfigs
}

func (w *WebProperty) GetOperatingSystems() []Attribute {
	if w == nil {
		return nil
	}
	return w.OperatingSystems
}

func (w *WebProperty) GetPort() *int {
	if w == nil {
		return nil
	}
	return w.Port
}

func (w *WebProperty) GetScanTime() *string {
	if w == nil {
		return nil
	}
	return w.ScanTime
}

func (w *WebProperty) GetSoftware() []Attribute {
	if w == nil {
		return nil
	}
	return w.Software
}

func (w *WebProperty) GetThreats() []Threat {
	if w == nil {
		return nil
	}
	return w.Threats
}

func (w *WebProperty) GetTLS() *TLS {
	if w == nil {
		return nil
	}
	return w.TLS
}

func (w *WebProperty) GetVulns() []Vuln {
	if w == nil {
		return nil
	}
	return w.Vulns
}
